
== CLI Tools ==

kafka-topics::
Verwalten von Topics
+
    kafka-topics --bootstrap-server localhost:9092 --create --topic=test --replication-factor=1 --partitions=1
    kafka-topics --bootstrap-server localhost:9092 --list
    kafka-topics --bootstrap-server localhost:9092 --describe --topic=test
    kafka-topics --bootstrap-server localhost:9092 --delete --topic=test

connect-standalone::
+
    connect-standalone \
        config/connect-standalone.properties \
        config/connect-file-source.properties \
        config/connect-file-sink.properties

kafka-console-producer::
Nimmt Nachrichten von stdin entgegen und schreibt sie auf ein Topic.
* Achtung: Versteht kein Avro, die Nachrichteninhalte werden also Binär angezeigt
+
    kafka-console-producer --broker-list=localhost:9092 --topic=test < DATA

kafka-console-consumer::
Zeigt die neuesten oder auf Wunsch alle Nachrichten auf der Konsole.
* Achtung: Versteht kein Avro, die Nachrichteninhalte werden also Binär angezeigt
* Achtung: Bleibt stillschweigend hängen wenn man eine Consumer-Group angibt, die bereits von einem anderen aktiven Client benutzt wird.
+
    kafka-console-consumer --bootstrap-server=localhost:9092 --topic=test
+
    kafka-console-consumer \
        --consumer.config=kafka-cli/kafka-dev.properties \
        --bootstrap-server=kafka-dev:9093,kafka-dev:9094 \
        --topic=mytopic-v2 \
        --group=mytopic-cg1 \
        --from-beginning \
        --property print.timestamp=true \
        --property print.key=true
+
|===
| --from-beginning              | zur Anzeige aller gespeicherter Nachrichten
| --property print.key=false    | Anzeige der Keys einer Nachricht
| --property print.value=true   | Anzeige der Werte einer Nachricht
| --property value.deserializer=org.apache.kafka.common.serialization.LongDeserializer | Auswahl eines alternativen Deserialisierers
|===

kafka-consumer-groups::
Verwalten von Consumer Groups (z.B. Resetten von Positionen)
+
    ./kafka-cli/kafka-consumer-groups-int \
        --reset-offsets --to-earliest --topic=foo --dry-run

    ./kafka-cli/kafka-consumer-groups-int \
        --offsets --verbose

    Die Scripte in kafka-cli/ sind nicht im GIT weil sie Zugangsdaten enthalten. Das o.g. Script sieht
    wie folgt aus:

        kafka-consumer-groups \
          --command-config=kafka-cli/kafka-int.properties \
          --bootstrap-server=kafka-int:9093 \
          --group=foo-cg1

        kafka-cli/kafka-int.properties
          security.protocol=SSL
          ssl.truststore.location=config/int-kafka-truststore.p12
          ssl.truststore.password=xxx
          ssl.keystore.location=config/int-kafka-keystore.p12
          ssl.keystore.password=xxx

kafkacat::
Feines Universaltool zum Lesen und Schreiben von Nachrichten
* Achtung: Avro wird nur im Consumer unterstützt, nicht für den Producer
+
|===
| -b            | Bootstrap broker(s)
| -C / -P       | Consumer / Producer u.a.
| -t            | Topic
| -K delimiter  | Trennzeichen für den Message Key
| -J            | JSON Formatierung
|===
+
    kafkacat  -b localhost:9092 -C -t streams-plaintext-output -J
+
    # Anzeige aller Messages im Topic "foo-test" als JSON
    kafkacat -b localhost:9192 -C -t foo-test -J
+
    # Erzeugen einer Message mit Key "64" und Message '{a:41}' auf Queue "foo-test"
    echo '64:{ "a": 41 }' | kafkacat -P -b localhost:9192 -t foo-test -K:
    cat beleg1.yml | yq -r - | kafkacat -P -b localhost:9192 -t foo-test
+
    # Zugriff auf Kafka mit SSL Client-Zertifikat (config/ und kafka-cli/ sind nicht in GIT!)
    kafkacat -v \
      -b kafka-int:9093 \
      -X security.protocol=SSL \
      -X ssl.ca.location=kafka-cli/kafka-int_root_ca.pem \
      -X ssl.keystore.location=config/int-kafka-keystore.p12 \
      -X ssl.keystore.password=xxx \
      -s avro -r 'https://kafka-schema-registry:9081' \
      -C -t foo
+
    # Mit Konfigurationsdatei
    cat kafkacat-dev.properties
        bootstrap.servers=kafka-dev:9093
        security.protocol=SSL
        ssl.ca.location=kafka-dev_root_ca.pem
        ssl.keystore.location=kafka-dev_keystore.p12
        ssl.keystore.password=secret
+
    # Mit Konfigurationsdatei
    kafkacat -F kafkacat-dev.properties -P -t mytopic
        <ein Wert pro Zeile>


avro-tool::
Werkzeug zum validieren und konvertieren von Avro Nachrichten. Hat keinen direkten Bezug zu Kafka!
+
    # Wandelt eine Avro Definition in das kanonische Format um (um zu sehen wo sich zwei Dateien signifikant unterscheiden)
    avro-tools canonical Foo.avsc Foo-canonical.asvc

kafka-avro-console-producer::
Kommt aus der Confluent Kafka Distribution und soll angeblich Avro verstehen können.
Konnte ihn aber nicht zum Laufen bringen.
+
    wget http://packages.confluent.io/archive/1.0/confluent-1.0.1-2.10.4.zip
    unzip confluent-1.0.1-2.10.4.zip
    cd confluent-1.0.1
    ./bin/kafka-avro-console-producer
        --broker-list kafka-dev:9093
        --topic mytopic
        --property schema.registry.url=https://user:pass@kafka-dev-schema-registry/
        --property value.schema=https://user:pass@kafka-dev-schema-registry/schemas/ids/83
