version: '2'

services:

  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
#    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
 #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
 #     KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
#      KAFKA_LISTENERS: LISTENER_INT://kafka:9093,LISTENER_EXT://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: LISTENER_INT://kafka:9093,LISTENER_EXT://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INT
    volumes:
      - ./data:/var/lib/kafka/data
      - ./config:/etc/kafka
    depends_on:
      - zookeeper
